### ISSUE TITLE
Implement assert.null()

### ISSUE THREAD

**Issue by ysbaddaden** [ysbaddaden/minitest-js#5]
It could be interesting to have an assertion against null and undefined interchangeably, but which wouldn't catch false or 0 or something else that's falsy.

Thought the following is impossible:

``` javascript
test.mustBeNull();
```

But that will work:

``` javascript
expect(test).toBeNull();
```

**Comment by ysbaddaden** [comment]
On the other end, it duplicates `assert.equal(null, test)`.

**Comment by ysbaddaden** [comment]
Will reopen for now.

**Comment by felippenardi** [comment]
Wouldn't it be interesting to use `.toBeNull()` as an alias of `assert.equal(null, test)`?

**Comment by ysbaddaden** [comment]
Not possible: in minitest an expectation needs an assertion to exist (see
expectations.js).

Anyway I'll add it, I think. assert_nil does exist in minitest, and having
an assert.null that matches both null and undefined would be interesting
(that isn't possible with assert.equal).

J.

**Comment by ysbaddaden** [comment]
Stupid me: `assert.equal` already accepts `null` and `undefined` interchangeably, but will fail when compared to anything else.

``` javascript
assert.equal(null, null);            // => success
assert.equal(undefined, undefined);  // => success
assert.equal(null, undefined);       // => success
assert.equal(undefined, null);       // => success
```

Also, the `assert.null` notation isn't compatible with legacy browsers too (IE9 doesn't support it, and I'm not sure about IE10) and would require to use the `assert["null"]` notation which is quite cumbersome.

I'm afraid that this feature won't make it into minitest.js.

**Comment by dougo** [comment]
How about `assert.isNull`?  It would be equivalent to `assert.same(null, ...)`, but I still think it might be a useful abbreviation (and the failure message could be more specific).

Also, I'm guessing `assert.undefined` has the same problem as `assert.null`, but how about `assert.defined` and `refute.defined`?
